return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master",
	lazy = false,
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"lua",
				"bash",
				"typescript",
				"javascript",
				"tsx",
				"python",
				"go",
				"ruby",
				"rust",
				"terraform",
				"hcl",
				"c",
				"cpp",
				"html",
				"css",
				"json",
				"yaml",
				"dockerfile",
				"markdown",
				"toml",
				"sql",
				"graphql",
				"proto",
				"vim",
				"vimdoc",
			},
			auto_install = false,
			highlight = {
				enable = true,
			},
		})
	end,
}
