# prefix
set -g prefix C-t
unbind C-b
bind C-t send-prefix

# general
set -sg escape-time 0
set -g mouse on
set -g history-limit 10000
bind r source-file "~/.config/tmux/tmux.conf" \; display "Reloaded!"

# window
bind c new-window
bind -r p select-window -t :-
bind -r n select-window -t :+

# pane
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# display
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# status bar
set -g status-position top
set -g status-justify centre
set -g status-interval 1
set -g status-bg "colour237"
set -g status-fg "colour229"
set -g status-left-length 150
set -g status-left "#[bg=colour166 fg=colour229] #S #[default] #[bg=colour172 fg=colour229] #(basename #{pane_current_path}) #[default] #[bg=colour72 fg=colour229] #(cd #{pane_current_path}; git branch --show-current 2>/dev/null || echo '-')#(cd #{pane_current_path}; git diff --quiet 2>/dev/null || echo '*') #[default]"
set -g status-right-length 150
set -g status-right "#{?client_prefix,#[bg=colour124 fg=colour229] PREFIX #[default] ,}#{?window_zoomed_flag,#[bg=colour124 fg=colour229] ZOOM #[default] ,}#[bg=colour132 fg=colour229] %m/%d %H:%M "
setw -g window-status-format "#[bg=colour66 fg=colour229] #I #W #[default]"
setw -g window-status-current-format "#[bg=colour124 fg=colour229] #I #W #[default]"

# pane border
set -g pane-border-style "fg=colour229"
set -g pane-active-border-style "fg=colour106"
set -g pane-border-status bottom
set -g pane-border-format "#{?pane_active,#[bg=colour106 fg=colour235],#[bg=colour229 fg=colour235]} #I.#P : #{pane_current_command} #[default]"

# clock
setw -g clock-mode-colour "colour132"

